/********************************************************************
* clasadict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error clasadict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableclasadict();
extern void G__cpp_setup_inheritanceclasadict();
extern void G__cpp_setup_typetableclasadict();
extern void G__cpp_setup_memvarclasadict();
extern void G__cpp_setup_globalclasadict();
extern void G__cpp_setup_memfuncclasadict();
extern void G__cpp_setup_funcclasadict();
extern void G__set_cpp_environmentclasadict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "clasa.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__clasadictLN_TClass;
extern G__linked_taginfo G__clasadictLN_TBuffer;
extern G__linked_taginfo G__clasadictLN_TMemberInspector;
extern G__linked_taginfo G__clasadictLN_TObject;
extern G__linked_taginfo G__clasadictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__clasadictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__clasadictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__clasadictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__clasadictLN_clasa;

/* STUB derived class for protected member access */
