//
// File generated by rootcint at Tue Jul 21 19:20:33 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME clasadict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "clasadict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void clasa_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_clasa(void *p = 0);
   static void *newArray_clasa(Long_t size, void *p);
   static void delete_clasa(void *p);
   static void deleteArray_clasa(void *p);
   static void destruct_clasa(void *p);
   static void streamer_clasa(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::clasa*)
   {
      ::clasa *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::clasa >(0);
      static ::ROOT::TGenericClassInfo 
         instance("clasa", ::clasa::Class_Version(), "./clasa.h", 9,
                  typeid(::clasa), DefineBehavior(ptr, ptr),
                  &::clasa::Dictionary, isa_proxy, 0,
                  sizeof(::clasa) );
      instance.SetNew(&new_clasa);
      instance.SetNewArray(&newArray_clasa);
      instance.SetDelete(&delete_clasa);
      instance.SetDeleteArray(&deleteArray_clasa);
      instance.SetDestructor(&destruct_clasa);
      instance.SetStreamerFunc(&streamer_clasa);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::clasa*)
   {
      return GenerateInitInstanceLocal((::clasa*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::clasa*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr clasa::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *clasa::Class_Name()
{
   return "clasa";
}

//______________________________________________________________________________
const char *clasa::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::clasa*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int clasa::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::clasa*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void clasa::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::clasa*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *clasa::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::clasa*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void clasa::Streamer(TBuffer &R__b)
{
   // Stream an object of class clasa.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> i;
      R__b.CheckByteCount(R__s, R__c, clasa::IsA());
   } else {
      R__c = R__b.WriteVersion(clasa::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << i;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void clasa::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class clasa.
      TClass *R__cl = ::clasa::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "i", &i);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_clasa(void *p) {
      return  p ? new(p) ::clasa : new ::clasa;
   }
   static void *newArray_clasa(Long_t nElements, void *p) {
      return p ? new(p) ::clasa[nElements] : new ::clasa[nElements];
   }
   // Wrapper around operator delete
   static void delete_clasa(void *p) {
      delete ((::clasa*)p);
   }
   static void deleteArray_clasa(void *p) {
      delete [] ((::clasa*)p);
   }
   static void destruct_clasa(void *p) {
      typedef ::clasa current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_clasa(TBuffer &buf, void *obj) {
      ((::clasa*)obj)->::clasa::Streamer(buf);
   }
} // end of namespace ROOT for class ::clasa

/********************************************************
* clasadict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableclasadict();

extern "C" void G__set_cpp_environmentclasadict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("clasa.h");
  G__cpp_reset_tagtableclasadict();
}
#include <new>
extern "C" int G__cpp_dllrevclasadict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* clasa */
static int G__clasadict_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((clasa*) G__getstructoffset())->seti((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__clasadict_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((clasa*) G__getstructoffset())->geti());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__clasadict_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   clasa* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new clasa[n];
     } else {
       p = new((void*) gvp) clasa[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new clasa;
     } else {
       p = new((void*) gvp) clasa;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__clasadictLN_clasa));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__clasadict_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) clasa::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__clasadict_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) clasa::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__clasadict_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) clasa::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__clasadict_168_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      clasa::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__clasadict_168_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((clasa*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__clasadict_168_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) clasa::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__clasadict_168_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) clasa::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__clasadict_168_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) clasa::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__clasadict_168_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) clasa::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__clasadict_168_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   clasa* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new clasa(*(clasa*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__clasadictLN_clasa));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef clasa G__Tclasa;
static int G__clasadict_168_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (clasa*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((clasa*) (soff+(sizeof(clasa)*i)))->~G__Tclasa();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (clasa*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((clasa*) (soff))->~G__Tclasa();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__clasadict_168_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   clasa* dest = (clasa*) G__getstructoffset();
   *dest = *(clasa*) libp->para[0].ref;
   const clasa& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* clasa */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncclasadict {
 public:
  G__Sizep2memfuncclasadict(): p(&G__Sizep2memfuncclasadict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncclasadict::*p)();
};

size_t G__get_sizep2memfuncclasadict()
{
  G__Sizep2memfuncclasadict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceclasadict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__clasadictLN_clasa))) {
     clasa *G__Lderived;
     G__Lderived=(clasa*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__clasadictLN_clasa),G__get_linked_tagnum(&G__clasadictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableclasadict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__clasadictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__clasadictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__clasadictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__clasadictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__clasadictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__clasadictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__clasadictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__clasadictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__clasadictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__clasadictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* clasa */
static void G__setup_memvarclasa(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__clasadictLN_clasa));
   { clasa *p; p=(clasa*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"i=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__clasadictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarclasadict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncclasa(void) {
   /* clasa */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__clasadictLN_clasa));
   G__memfunc_setup("seti",437,G__clasadict_168_0_1, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("geti",425,G__clasadict_168_0_2, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clasa",516,G__clasadict_168_0_3, 105, G__get_linked_tagnum(&G__clasadictLN_clasa), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__clasadict_168_0_4, 85, G__get_linked_tagnum(&G__clasadictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&clasa::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__clasadict_168_0_5, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&clasa::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__clasadict_168_0_6, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&clasa::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__clasadict_168_0_7, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&clasa::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__clasadictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__clasadict_168_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__clasadict_168_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&clasa::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__clasadict_168_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&clasa::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__clasadict_168_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&clasa::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__clasadict_168_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&clasa::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("clasa", 516, G__clasadict_168_0_16, (int) ('i'), G__get_linked_tagnum(&G__clasadictLN_clasa), -1, 0, 1, 1, 1, 0, "u 'clasa' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~clasa", 642, G__clasadict_168_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__clasadict_168_0_18, (int) ('u'), G__get_linked_tagnum(&G__clasadictLN_clasa), -1, 1, 1, 1, 1, 0, "u 'clasa' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncclasadict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalclasadict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcclasadict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__clasadictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__clasadictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__clasadictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__clasadictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__clasadictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__clasadictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__clasadictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__clasadictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__clasadictLN_clasa = { "clasa" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableclasadict() {
  G__clasadictLN_TClass.tagnum = -1 ;
  G__clasadictLN_TBuffer.tagnum = -1 ;
  G__clasadictLN_TMemberInspector.tagnum = -1 ;
  G__clasadictLN_TObject.tagnum = -1 ;
  G__clasadictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__clasadictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__clasadictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__clasadictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__clasadictLN_clasa.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableclasadict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__clasadictLN_TClass);
   G__get_linked_tagnum_fwd(&G__clasadictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__clasadictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__clasadictLN_TObject);
   G__get_linked_tagnum_fwd(&G__clasadictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__clasadictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__clasadictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__clasadictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__clasadictLN_clasa),sizeof(clasa),-1,29952,(char*)NULL,G__setup_memvarclasa,G__setup_memfuncclasa);
}
extern "C" void G__cpp_setupclasadict(void) {
  G__check_setup_version(30051515,"G__cpp_setupclasadict()");
  G__set_cpp_environmentclasadict();
  G__cpp_setup_tagtableclasadict();

  G__cpp_setup_inheritanceclasadict();

  G__cpp_setup_typetableclasadict();

  G__cpp_setup_memvarclasadict();

  G__cpp_setup_memfuncclasadict();
  G__cpp_setup_globalclasadict();
  G__cpp_setup_funcclasadict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncclasadict();
  return;
}
class G__cpp_setup_initclasadict {
  public:
    G__cpp_setup_initclasadict() { G__add_setup_func("clasadict",(G__incsetup)(&G__cpp_setupclasadict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initclasadict() { G__remove_setup_func("clasadict"); }
};
G__cpp_setup_initclasadict G__cpp_setup_initializerclasadict;

